# Entendendo os dados

In [1]:
#Importações necessárias
import pandas as pd
import numpy as np

In [ ]:
#Carregando o dataset
df = pd.read_csv('../data/raw/ecommerce_data.csv')

In [ ]:
#Analisando as primeiras linhas do dataset
df.head(10)

,OrderID,Product,Category,Brand,Platform,City,Price,Quantity,TotalAmount,Rating,Reviews,OrderDate
0,ORD100000,Samsung Galaxy A14,Electronics,Samsung,Souq,Cairo,16284.02,1,16284.02,1.39,1684,2024-11-11
1,ORD100001,Nike Air Max,Fashion,Nike,Jumia,Alexandria,6645.20,2,13290.40,2.56,3604,2024-06-22
2,ORD100002,Bluetooth Headset,Accessories,JBL,Jumia,Casablanca,8882.92,3,26648.76,4.98,1257,2024-05-27
3,ORD100003,HP Pavilion Laptop,Computers,HP,Souq,Dubai,3665.44,1,3665.44,1.44,662,2024-07-25
4,ORD100004,iPhone 13,Electronics,Apple,Souq,Casablanca,5210.37,2,10420.74,3.73,2424,2024-02-19
5,ORD100005,T-shirt Cotton,Fashion,Generic,Souq,Riyadh,19869.86,5,99349.30,3.91,2154,2024-09-28
6,ORD100006,T-shirt Cotton,Fashion,Generic,Souq,Casablanca,17796.11,2,35592.22,4.18,4309,2024-07-02
7,ORD100007,Smartwatch FitPro,Wearables,FitPro,Souq,Casablanca,13081.14,3,39243.42,2.98,3504,2024-01-30
8,ORD100008,T-shirt Cotton,Fashion,Generic,Amazon,Dubai,510.30,5,2551.50,1.17,178,2024-09-21
9,ORD100009,Xiaomi Redmi Note 12,Electronics,Xiaomi,Jumia,Riyadh,6326.57,3,18979.71,2.05,4589,2024-09-26

In [ ]:
#Analisando as últimas linhas do dataset
df.tail(10)

,OrderID,Product,Category,Brand,Platform,City,Price,Quantity,TotalAmount,Rating,Reviews,OrderDate
9990,ORD109990,Samsung Galaxy A14,Electronics,Samsung,Souq,Casablanca,3397.33,4,13589.32,1.37,370,2024-02-10
9991,ORD109991,iPhone 13,Electronics,Apple,Jumia,Alexandria,5108.58,5,25542.90,4.13,1586,2024-09-03
9992,ORD109992,Nike Air Max,Fashion,Nike,Jumia,Cairo,12745.76,3,38237.28,3.09,785,2024-06-14
9993,ORD109993,iPhone 13,Electronics,Apple,Souq,Casablanca,19530.95,4,78123.80,4.34,4356,2024-04-10
9994,ORD109994,Adidas Running Shoes,Fashion,Adidas,Jumia,Cairo,6384.43,3,19153.29,3.04,2551,2024-05-16
9995,ORD109995,HP Pavilion Laptop,Computers,HP,Jumia,Riyadh,3571.93,1,3571.93,1.05,2154,2024-05-21
9996,ORD109996,Adidas Running Shoes,Fashion,Adidas,Souq,Cairo,2974.55,4,11898.20,2.60,1796,2024-11-27
9997,ORD109997,Adidas Running Shoes,Fashion,Adidas,Amazon,Riyadh,8646.20,1,8646.20,3.20,4001,2024-10-15
9998,ORD109998,T-shirt Cotton,Fashion,Generic,Amazon,Riyadh,4960.53,4,19842.12,3.42,685,2024-04-26
9999,ORD109999,Bluetooth Headset,Accessories,JBL,Jumia,Casablanca,13811.49,5,69057.45,2.84,488,2024-01-15

In [5]:
#Vendo as dimensões do dataset
print(f"O dataset possui {df.shape[0]} linhas e {df.shape[1]} colunas.")

O dataset possui 10000 linhas e 12 colunas.

In [6]:
#Analisando os tipos das colunas
print("Tipos das colunas:")
print(df.dtypes)

Tipos das colunas:
OrderID            str
Product            str
Category           str
Brand              str
Platform           str
City               str
Price          float64
Quantity         int64
TotalAmount    float64
Rating         float64
Reviews          int64
OrderDate          str
dtype: object

In [8]:
#Informações gerais do dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   OrderID      10000 non-null  str
 1   Product      10000 non-null  str
 2   Category     10000 non-null  str
 3   Brand        10000 non-null  str
 4   Platform     10000 non-null  str
 5   City         10000 non-null  str
 6   Price        10000 non-null  float64
 7   Quantity     10000 non-null  int64
 8   TotalAmount  10000 non-null  float64
 9   Rating       10000 non-null  float64
 10  Reviews      10000 non-null  int64
 11  OrderDate    10000 non-null  str
dtypes: float64(3), int64(2), str(7)
memory usage: 1.5 MB

In [9]:
#Analisando as estatísticas descritivas do dataset
df.describe()

              Price      Quantity   TotalAmount        Rating       Reviews
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000
mean   10027.986331      3.006200  30199.572439      3.005592   2520.072200
std     5728.261196      1.415472  23861.789828      1.154845   1443.849734
min      105.590000      1.000000    113.550000      1.000000      0.000000
25%     4999.862500      2.000000  11066.910000      2.010000   1275.000000
50%    10063.600000      3.000000  23671.630000      3.005000   2537.500000
75%    14938.430000      4.000000  44648.580000      4.000000   3767.000000
max    19999.340000      5.000000  99993.800000      5.000000   5000.000000

In [10]:
#Verificando nulos no dataset
print("Número de valores nulos por coluna:")
print(df.isnull().sum())

Número de valores nulos por coluna:
OrderID        0
Product        0
Category       0
Brand          0
Platform       0
City           0
Price          0
Quantity       0
TotalAmount    0
Rating         0
Reviews        0
OrderDate      0
dtype: int64

In [12]:
#Verificando valores duplicados no dataset
print(f"Número de linhas duplicadas: {df.duplicated().sum()}")

Número de linhas duplicadas: 0

In [13]:
#Verificando a quantidade de valores únicos em cada coluna
print("Quantidade de valores únicos em cada coluna:")
print(df.nunique())

Quantidade de valores únicos em cada coluna:
OrderID        10000
Product           10
Category           5
Brand             10
Platform           3
City               6
Price           9975
Quantity           5
TotalAmount     9994
Rating           401
Reviews         4318
OrderDate        361
dtype: int64

In [14]:
#Verificando a frequência de cada categoria na coluna 'Category'
print("Frequência de cada categoria na coluna 'Category':")
print(df['Category'].value_counts())

Frequência de cada categoria na coluna 'Category':
Category
Electronics    3028
Fashion        2970
Computers      1953
Accessories    1029
Wearables      1020
Name: count, dtype: int64

In [15]:
#Verificando a distribuição de valores
df['Price'].describe()

count    10000.000000
mean     10027.986331
std       5728.261196
min        105.590000
25%       4999.862500
50%      10063.600000
75%      14938.430000
max      19999.340000
Name: Price, dtype: float64

In [ ]:
#Conferindo o formato da coluna 'OrderDate'
df['OrderDate'].head()

0    2024-11-11
1    2024-06-22
2    2024-05-27
3    2024-07-25
4    2024-02-19
Name: OrderDate, dtype: str

In [17]:
#Convertendo a coluna 'OrderDate' para o tipo datetime
df['OrderDate'] = pd.to_datetime(df['OrderDate'])

In [18]:
#Conferindo se a conversão foi bem-sucedida
df['OrderDate'].head()

0   2024-11-11
1   2024-06-22
2   2024-05-27
3   2024-07-25
4   2024-02-19
Name: OrderDate, dtype: datetime64[us]

In [19]:
#Conferindo o intervalo de datas
print(f"Data mínima: {df['OrderDate'].min()}")
print(f"Data máxima: {df['OrderDate'].max()}")

Data mínima: 2024-01-01 00:00:00
Data máxima: 2024-12-26 00:00:00

In [22]:
#Exemplo aleátorio de uma linha do dataset
print("Exemplo aleatório de uma linha do dataset:")
print(df.sample(3))

Exemplo aleatório de uma linha do dataset:
        OrderID               Product   Category   Brand Platform        City  \
5233  ORD105233  Adidas Running Shoes    Fashion  Adidas    Jumia      Riyadh
6979  ORD106979          Nike Air Max    Fashion    Nike   Amazon        Giza
1924  ORD101924    HP Pavilion Laptop  Computers      HP     Souq  Casablanca

        Price  Quantity  TotalAmount  Rating  Reviews  OrderDate
5233  6204.96         5     31024.80    1.86     2839 2024-05-13
6979   471.38         1       471.38    1.00     2774 2024-09-25
1924  5119.10         2     10238.20    3.74      558 2024-05-29

# Conclusões da Etapa de Entendimento dos Dados

- O dataset possui 10.000 registros e 12 colunas.
- Não foram encontrados valores nulos ou registros duplicados.
- A coluna `OrderDate` foi convertida corretamente para o formato datetime.
- Os tipos das variáveis estão adequados para análises futuras.
- As categorias `Electronics` e `Fashion` representam a maior parte dos registros.
- O dataset possui boa qualidade geral e está preparado para a etapa de análise exploratória.
- Foram identificadas oportunidades interessantes para análises temporais, geográficas e de performance de produtos.